import type { Order, Course, LiveEvent } from '@/types';

export const instructorStats = {
  totalRevenue: 684500,
  monthlyRevenue: 142000,
  activeStudents: 187,
  publishedCourses: 4,
  upcomingLives: 2,
  monthlySales: 23,
};

export const instructorCourses: Course[] = [
  {
    id: 'ic1',
    slug: 'instructor-course-1',
    title: 'Excel az alapoktól a magabiztos használatig',
    shortDescription: 'Tanuld meg az Excel alapjait és haladó funkcióit.',
    description: '',
    category: 'Üzlet és vállalkozás',
    categorySlug: 'uzlet-es-vallalkozas',
    instructorId: 'i1',
    instructorName: 'Kovács Anna',
    price: 24900,
    rating: 4.9,
    reviewCount: 312,
    studentCount: 1840,
    durationMinutes: 720,
    difficulty: 'kezdő',
    type: 'mixed',
    hasDownloadableMaterials: true,
    hasLiveSession: false,
    coverColor: '#365288',
    lastUpdated: '2026-07-15',
    benefits: [],
    sections: [],
    reviews: [],
    status: 'kozzeteva',
  },
  {
    id: 'ic2',
    slug: 'instructor-course-2',
    title: 'Pénzügyi tervezés vállalkozóknak',
    shortDescription: 'Tanuld meg a vállalkozás pénzügyi tervezését.',
    description: '',
    category: 'Pénzügy',
    categorySlug: 'penzugy',
    instructorId: 'i1',
    instructorName: 'Kovács Anna',
    price: 38900,
    rating: 4.8,
    reviewCount: 145,
    studentCount: 620,
    durationMinutes: 480,
    difficulty: 'kozepes',
    type: 'mixed',
    hasDownloadableMaterials: true,
    hasLiveSession: false,
    coverColor: '#2b426d',
    lastUpdated: '2026-06-10',
    benefits: [],
    sections: [],
    reviews: [],
    status: 'kozzeteva',
  },
  {
    id: 'ic3',
    slug: 'instructor-course-3',
    title: 'Excel haladóknak - Adatelemzés',
    shortDescription: 'Mélyítsd el Excel tudásodat adatelemzés terén.',
    description: '',
    category: 'Üzlet és vállalkozás',
    categorySlug: 'uzlet-es-vallalkozas',
    instructorId: 'i1',
    instructorName: 'Kovács Anna',
    price: 34900,
    rating: 0,
    reviewCount: 0,
    studentCount: 0,
    durationMinutes: 600,
    difficulty: 'halado',
    type: 'video',
    hasDownloadableMaterials: false,
    hasLiveSession: false,
    coverColor: '#365488',
    lastUpdated: '2026-08-01',
    benefits: [],
    sections: [],
    reviews: [],
    status: 'jovahagyasra-var',
  },
  {
    id: 'ic4',
    slug: 'instructor-course-4',
    title: 'Pénzügyi függetlenség alapjai',
    shortDescription: 'Tanuld meg a személyes pénzügyek alapjait.',
    description: '',
    category: 'Pénzügy',
    categorySlug: 'penzugy',
    instructorId: 'i1',
    instructorName: 'Kovács Anna',
    price: 0,
    rating: 0,
    reviewCount: 0,
    studentCount: 0,
    durationMinutes: 0,
    difficulty: 'kezdő',
    type: 'video',
    hasDownloadableMaterials: false,
    hasLiveSession: false,
    coverColor: '#2b426d',
    lastUpdated: '2026-08-03',
    benefits: [],
    sections: [],
    reviews: [],
    status: 'piszkozat',
  },
];

export const instructorLiveEvents: LiveEvent[] = [
  {
    id: 'ile1',
    slug: 'instructor-live-1',
    title: 'Kezdő Excel élő workshop',
    shortDescription: 'Interaktív élő workshop.',
    description: '',
    category: 'Üzlet és vállalkozás',
    categorySlug: 'uzlet-es-vallalkozas',
    instructorId: 'i1',
    instructorName: 'Kovács Anna',
    type: 'workshop',
    date: '2026-08-15',
    startTime: '17:00',
    endTime: '20:00',
    timezone: 'Europe/Budapest',
    price: 12900,
    maxParticipants: 25,
    registeredParticipants: 18,
    durationMinutes: 180,
    agenda: [],
    equipment: [],
    recordingAvailable: true,
    recordingAccessDays: 30,
    cancellationPolicy: '',
    status: 'meghirdetve',
    coverColor: '#365488',
  },
  {
    id: 'ile2',
    slug: 'instructor-live-2',
    title: 'Excel haladó konzultáció',
    shortDescription: 'Élő konzultáció haladó Excel kérdésekben.',
    description: '',
    category: 'Üzlet és vállalkozás',
    categorySlug: 'uzlet-es-vallalkozas',
    instructorId: 'i1',
    instructorName: 'Kovács Anna',
    type: 'konzultacio',
    date: '2026-08-22',
    startTime: '18:00',
    endTime: '19:30',
    timezone: 'Europe/Budapest',
    price: 9900,
    maxParticipants: 10,
    registeredParticipants: 0,
    durationMinutes: 90,
    agenda: [],
    equipment: [],
    recordingAvailable: false,
    cancellationPolicy: '',
    status: 'jovahagyasra-var',
    coverColor: '#365488',
  },
];

export const instructorOrders: Order[] = [
  {
    id: 'io1',
    date: '2026-08-03',
    itemTitle: 'Excel az alapoktól a magabiztos használatig',
    itemType: 'course',
    amount: 24900,
    status: 'fizetve',
    itemId: 'ic1',
  },
  {
    id: 'io2',
    date: '2026-08-02',
    itemTitle: 'Pénzügyi tervezés vállalkozóknak',
    itemType: 'course',
    amount: 38900,
    status: 'fizetve',
    itemId: 'ic2',
  },
  {
    id: 'io3',
    date: '2026-08-01',
    itemTitle: 'Kezdő Excel élő workshop',
    itemType: 'live',
    amount: 12900,
    status: 'fizetve',
    itemId: 'ile1',
  },
  {
    id: 'io4',
    date: '2026-07-31',
    itemTitle: 'Excel az alapoktól a magabiztos használatig',
    itemType: 'course',
    amount: 24900,
    status: 'fizetve',
    itemId: 'ic1',
  },
];
