import type { LiveEvent } from '@/types';

export const liveEvents: LiveEvent[] = [
  {
    id: 'le1',
    slug: 'kezdo-excel-elo-workshop',
    title: 'Kezdő Excel élő workshop',
    shortDescription:
      'Interaktív élő workshop, ahol az Excel alapjait gyakoroljuk közösen.',
    description:
      'Ez a 3 órás interaktív workshop az Excel alapjait mutatja be. A résztvevők közösen dolgoznak feladatokon, és az oktató valós időben válaszolja meg a kérdéseket. A workshop végén minden résztvevő kap egy letölthető segédletet.',
    category: 'Üzlet és vállalkozás',
    categorySlug: 'uzlet-es-vallalkozas',
    instructorId: 'i1',
    instructorName: 'Kovács Anna',
    type: 'workshop',
    date: '2026-08-15',
    startTime: '17:00',
    endTime: '20:00',
    timezone: 'Europe/Budapest',
    price: 12900,
    maxParticipants: 25,
    registeredParticipants: 18,
    durationMinutes: 180,
    agenda: [
      '17:00 - Excel felület és navigáció',
      '17:45 - Cellák, formázás, alap képletek',
      '18:30 - Szünet',
      '18:45 - Függvények (SUM, AVERAGE, IF)',
      '19:30 - Gyakorló feladatok és Q&A',
    ],
    equipment: ['Számítógép internetkapcsolattal', 'Microsoft Excel vagy Google Sheets', 'Fejhallgató (opcionális)'],
    recordingAvailable: true,
    recordingAccessDays: 30,
    cancellationPolicy:
      'Az esemény előtt 48 órával ingyenesen lemondható. 48 órán belül a részvételi díj nem kerül visszatérítésre.',
    status: 'meghirdetve',
    coverColor: '#365488',
  },
  {
    id: 'le2',
    slug: 'angol-tarsalgasi-klub',
    title: 'Angol társalgási klub',
    shortDescription:
      'Heti társalgási klub, ahol angolul beszélgetünk különböző témákról.',
    description:
      'Az angol társalgási klub heti rendszerességgel találkozik. Minden alkalommal más témát dolgozunk fel, és a résztvevők párokban vagy kisebb csoportokban beszélgetnek. Kezdőtől haladó szintig mindenkit várunk.',
    category: 'Nyelvek',
    categorySlug: 'nyelvek',
    instructorId: 'i4',
    instructorName: 'Tóth Márton',
    type: 'interaktiv-ora',
    date: '2026-08-10',
    startTime: '18:00',
    endTime: '19:30',
    timezone: 'Europe/Budapest',
    price: 4900,
    maxParticipants: 15,
    registeredParticipants: 12,
    durationMinutes: 90,
    agenda: [
      '18:00 - Téma bemutatása',
      '18:15 - Szókártyák és kifejezések',
      '18:30 - Páros társalgás',
      '19:00 - Csoportos megbeszélés',
      '19:20 - Visszajelzés és házi feladat',
    ],
    equipment: ['Számítógép mikrofonnal', 'Internetkapcsolat', 'Webcam (opcionális)'],
    recordingAvailable: false,
    cancellationPolicy:
      'Az esemény előtt 24 órával ingyenesen lemondható. 24 órán belül a díj nem kerül visszatérítésre.',
    status: 'meghirdetve',
    coverColor: '#ff9d37',
  },
  {
    id: 'le3',
    slug: 'vallalkozasinditas-lepesrol-lepesre-elo',
    title: 'Vállalkozásindítás lépésről lépésre',
    shortDescription:
      'Élő webinar a vállalkozásindítás lépéseiről és buktatóiról.',
    description:
      'Ez a 2 órás webinar a vállalkozásindítás teljes folyamatát mutatja be az ötlettől az indulásig. Az oktató megosztja saját tapasztalatait, és válaszol a résztvevők kérdéseire.',
    category: 'Üzlet és vállalkozás',
    categorySlug: 'uzlet-es-vallalkozas',
    instructorId: 'i8',
    instructorName: 'Varga Tamás',
    type: 'webinar',
    date: '2026-08-20',
    startTime: '19:00',
    endTime: '21:00',
    timezone: 'Europe/Budapest',
    price: 7900,
    maxParticipants: 100,
    registeredParticipants: 64,
    durationMinutes: 120,
    agenda: [
      '19:00 - Ötletvalidálás és piackutatás',
      '19:30 - Üzleti terv és jogi formák',
      '20:00 - Finanszírozási lehetőségek',
      '20:30 - Q&A',
    ],
    equipment: ['Számítógép internetkapcsolattal', 'Jegyzetelő eszköz'],
    recordingAvailable: true,
    recordingAccessDays: 14,
    cancellationPolicy:
      'Az esemény előtt 48 órával ingyenesen lemondható.',
    status: 'meghirdetve',
    coverColor: '#365488',
  },
  {
    id: 'le4',
    slug: 'kozossegi-media-hirdetesek-eloben',
    title: 'Közösségi média hirdetések élőben',
    shortDescription:
      'Élő workshop Facebook és Instagram hirdetések beállításáról.',
    description:
      'Ez a workshop a Facebook és Instagram hirdetések beállítását és optimalizálását mutatja be a gyakorlatban. A résztvevők saját kampányokat hozhatnak létre az oktató iránymutatásával.',
    category: 'Marketing',
    categorySlug: 'marketing',
    instructorId: 'i3',
    instructorName: 'Szabó Dóra',
    type: 'workshop',
    date: '2026-08-18',
    startTime: '16:00',
    endTime: '19:00',
    timezone: 'Europe/Budapest',
    price: 15900,
    maxParticipants: 20,
    registeredParticipants: 20,
    durationMinutes: 180,
    agenda: [
      '16:00 - Hirdetésfiók beállítása',
      '16:45 - Célközönség meghatározása',
      '17:30 - Szünet',
      '17:45 - Kreatív anyagok és kampányok',
      '18:30 - Mérés és optimalizálás',
    ],
    equipment: ['Számítógép internetkapcsolattal', 'Facebook Business fiók', 'Kreatív anyagok (képek)'],
    recordingAvailable: true,
    recordingAccessDays: 21,
    cancellationPolicy:
      'Az esemény előtt 72 órával ingyenesen lemondható. 72 órán belül a díj nem kerül visszatérítésre.',
    status: 'betelt',
    coverColor: '#ff7f0f',
  },
  {
    id: 'le5',
    slug: 'matematika-erettsegi-konzultacio',
    title: 'Matematika érettségi konzultáció',
    shortDescription:
      'Élő konzultáció az érettségi matematika vizsga előtt.',
    description:
      'Ez a konzultáció az érettségi matematika vizsga előtt nyújt utolsó felkészülési lehetőséget. Az oktató a leggyakoribb feladattípusokat veszi át, és válaszol a hallgatók kérdéseire.',
    category: 'Érettségi felkészítés',
    categorySlug: 'erettsegi-felkeszites',
    instructorId: 'i6',
    instructorName: 'Kiss Gábor',
    type: 'konzultacio',
    date: '2026-08-25',
    startTime: '17:00',
    endTime: '19:00',
    timezone: 'Europe/Budapest',
    price: 6900,
    maxParticipants: 30,
    registeredParticipants: 22,
    durationMinutes: 120,
    agenda: [
      '17:00 - Leggyakoribb feladattípusok',
      '17:45 - Feladatok megoldása közösen',
      '18:30 - Tippek és trükkök a vizsgán',
      '19:00 - Q&A',
    ],
    equipment: ['Számítógép internetkapcsolattal', 'Számológép', 'Jegyzetelő eszköz'],
    recordingAvailable: true,
    recordingAccessDays: 30,
    cancellationPolicy:
      'Az esemény előtt 48 órával ingyenesen lemondható.',
    status: 'meghirdetve',
    coverColor: '#f0610a',
  },
  {
    id: 'le6',
    slug: 'kerttervezes-kezdoknek',
    title: 'Kerttervezés kezdőknek',
    shortDescription:
      'Interaktív óra a kerttervezés alapjairól és növényválasztásról.',
    description:
      'Ez az interaktív óra a kerttervezés alapjait mutatja be: talaj, növényválasztás, elrendezés és karbantartás. A résztvevők kérdéseket tehetnek fel és megbeszélhetik saját kertjük terveit.',
    category: 'Kreatív készségek',
    categorySlug: 'kreativ-keszsegek',
    instructorId: 'i5',
    instructorName: 'Varga Eszter',
    type: 'interaktiv-ora',
    date: '2026-08-12',
    startTime: '18:00',
    endTime: '20:00',
    timezone: 'Europe/Budapest',
    price: 8900,
    maxParticipants: 20,
    registeredParticipants: 8,
    durationMinutes: 120,
    agenda: [
      '18:00 - Kerttervezés alapelvei',
      '18:30 - Talaj és növényválasztás',
      '19:00 - Elrendezés és kompozíció',
      '19:30 - Egyéni konzultáció',
    ],
    equipment: ['Számítógép internetkapcsolattal', 'Jegyzetelő eszköz', 'Saját kert tervrajza (opcionális)'],
    recordingAvailable: false,
    cancellationPolicy:
      'Az esemény előtt 48 órával ingyenesen lemondható.',
    status: 'meghirdetve',
    coverColor: '#9bb5d8',
  },
];

export function getLiveEvent(slug: string): LiveEvent | undefined {
  return liveEvents.find((e) => e.slug === slug);
}
